/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.jpa.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.example.jpa.jooq.Keys;
import org.jooq.example.jpa.jooq.Public;
import org.jooq.example.jpa.jooq.tables.records.CcRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cc extends TableImpl<CcRecord> {

    private static final long serialVersionUID = -1762753943;

    /**
     * The reference instance of <code>PUBLIC.CC</code>
     */
    public static final Cc CC = new Cc();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CcRecord> getRecordType() {
        return CcRecord.class;
    }

    /**
     * The column <code>PUBLIC.CC.ID</code>.
     */
    public final TableField<CcRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("(NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_87F29A23_4313_41C7_A0B1_D0D498414C74)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.CC.TEXT</code>.
     */
    public final TableField<CcRecord, String> TEXT = createField("TEXT", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>PUBLIC.CC.PARENT_ID</code>.
     */
    public final TableField<CcRecord, Integer> PARENT_ID = createField("PARENT_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>PUBLIC.CC</code> table reference
     */
    public Cc() {
        this(DSL.name("CC"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.CC</code> table reference
     */
    public Cc(String alias) {
        this(DSL.name(alias), CC);
    }

    /**
     * Create an aliased <code>PUBLIC.CC</code> table reference
     */
    public Cc(Name alias) {
        this(alias, CC);
    }

    private Cc(Name alias, Table<CcRecord> aliased) {
        this(alias, aliased, null);
    }

    private Cc(Name alias, Table<CcRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CcRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CcRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_86;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CcRecord>> getKeys() {
        return Arrays.<UniqueKey<CcRecord>>asList(Keys.CONSTRAINT_86);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CcRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CcRecord, ?>>asList(Keys.FKI7XHHMC0Y03KEL62MTI7AJWXI);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Cc as(String alias) {
        return new Cc(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Cc as(Name alias) {
        return new Cc(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Cc rename(String name) {
        return new Cc(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cc rename(Name name) {
        return new Cc(name, null);
    }
}
