/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.jpa.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.example.jpa.jooq.Keys;
import org.jooq.example.jpa.jooq.Public;
import org.jooq.example.jpa.jooq.tables.records.DdRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dd extends TableImpl<DdRecord> {

    private static final long serialVersionUID = -1395730117;

    /**
     * The reference instance of <code>PUBLIC.DD</code>
     */
    public static final Dd DD = new Dd();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DdRecord> getRecordType() {
        return DdRecord.class;
    }

    /**
     * The column <code>PUBLIC.DD.ID</code>.
     */
    public final TableField<DdRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("(NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_3ECFD423_17E3_47D7_8776_165D26418027)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.DD.TEXT</code>.
     */
    public final TableField<DdRecord, String> TEXT = createField("TEXT", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>PUBLIC.DD.PARENT_ID</code>.
     */
    public final TableField<DdRecord, Integer> PARENT_ID = createField("PARENT_ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>PUBLIC.DD</code> table reference
     */
    public Dd() {
        this(DSL.name("DD"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.DD</code> table reference
     */
    public Dd(String alias) {
        this(DSL.name(alias), DD);
    }

    /**
     * Create an aliased <code>PUBLIC.DD</code> table reference
     */
    public Dd(Name alias) {
        this(alias, DD);
    }

    private Dd(Name alias, Table<DdRecord> aliased) {
        this(alias, aliased, null);
    }

    private Dd(Name alias, Table<DdRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DdRecord, Integer> getIdentity() {
        return Keys.IDENTITY_DD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DdRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_88;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DdRecord>> getKeys() {
        return Arrays.<UniqueKey<DdRecord>>asList(Keys.CONSTRAINT_88);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DdRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DdRecord, ?>>asList(Keys.FKAWQPTEP76F0TMYECFVS27DKLP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Dd as(String alias) {
        return new Dd(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Dd as(Name alias) {
        return new Dd(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Dd rename(String name) {
        return new Dd(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Dd rename(Name name) {
        return new Dd(name, null);
    }
}
