/*
 * This file is generated by jOOQ.
*/
package org.jooq.example.jpa.jooq;


import javax.annotation.Generated;

import org.jooq.example.jpa.jooq.tables.Aa;
import org.jooq.example.jpa.jooq.tables.Actor;
import org.jooq.example.jpa.jooq.tables.Bb;
import org.jooq.example.jpa.jooq.tables.Cc;
import org.jooq.example.jpa.jooq.tables.Dd;
import org.jooq.example.jpa.jooq.tables.Film;
import org.jooq.example.jpa.jooq.tables.FilmActor;
import org.jooq.example.jpa.jooq.tables.Language;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.AA</code>.
     */
    public static final Aa AA = org.jooq.example.jpa.jooq.tables.Aa.AA;

    /**
     * The table <code>PUBLIC.ACTOR</code>.
     */
    public static final Actor ACTOR = org.jooq.example.jpa.jooq.tables.Actor.ACTOR;

    /**
     * The table <code>PUBLIC.BB</code>.
     */
    public static final Bb BB = org.jooq.example.jpa.jooq.tables.Bb.BB;

    /**
     * The table <code>PUBLIC.CC</code>.
     */
    public static final Cc CC = org.jooq.example.jpa.jooq.tables.Cc.CC;

    /**
     * The table <code>PUBLIC.DD</code>.
     */
    public static final Dd DD = org.jooq.example.jpa.jooq.tables.Dd.DD;

    /**
     * The table <code>PUBLIC.FILM</code>.
     */
    public static final Film FILM = org.jooq.example.jpa.jooq.tables.Film.FILM;

    /**
     * The table <code>PUBLIC.FILM_ACTOR</code>.
     */
    public static final FilmActor FILM_ACTOR = org.jooq.example.jpa.jooq.tables.FilmActor.FILM_ACTOR;

    /**
     * The table <code>PUBLIC.LANGUAGE</code>.
     */
    public static final Language LANGUAGE = org.jooq.example.jpa.jooq.tables.Language.LANGUAGE;
}
